language: "ja-JP"
reviews:
  profile: "chill"
  high_level_summary: true
  path_filters:
    - "!**/dist/**"
    - "!**/vendor/**"
    - "!**/node_modules/**"
    - "!**/*.min.js"
    - "!**/*.min.css"
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - master
    auto_incremental_review: false
instructions: |-
  ## AI 向けルール

  特定の関数やメソッドについて、PHPUnit テストを追加する時には、
  多数の条件で正しい結果を返すかをテストしたり、条件と結果の組み合わせを簡単に増やせるようにするために、
  テスト条件と期待する結果を配列で記載し、その配列をループしながらテストを実行する形式で書いてください。

  基本的な形式の例としては、
  例えばあらかじめテスト用の投稿（id=1）を作った上で
  以下のように書いて、function_name() が期待する値を返すかどうかのテストします。
  ただ、あくまで $test_cases の中身の配列は一つの例なので、
  実際にはテストしたい関数やメソッドに応じて適切な条件や期待する結果を設定してください。
  
  ```
  function test_function_name() {
    $test_cases = array(
      array(
        'test_condition_name' => 'test_function_name',
        'conditions'          => array(
          'options'   => array(
            'test_option_name1' => 'test_option_value1',
            'test_option_name2' => 'test_option_value2',
          ),
          'post_id'   => 1,
          'post_meta' => array(
            'test_post_meta_name' => 'test_post_meta_value',
          ),
        ),
        'target_url'          => home_url( '/' ) . '?p=1',
        'expected'            => true,
      ),
    );

    foreach ( $test_cases as $case ) {
      if ( ! empty( $case['conditions']['options'] ) && is_array( $case['conditions']['options'] ) ) {
        foreach ( $case['conditions']['options'] as $option_name => $option_value ) {
          update_option( $option_name, $option_value );
        }
      }
      if ( ! empty( $case['conditions']['post_id'] ) ) {
        if ( ! empty( $case['conditions']['post_meta'] ) && is_array( $case['conditions']['post_meta'] ) ) {
          foreach ( $case['conditions']['post_meta'] as $post_meta_name => $post_meta_value ) {
            if ( '' === $post_meta_value || null === $post_meta_value ) {
              delete_post_meta( $case['conditions']['post_id'], $post_meta_name );
            } else {
              update_post_meta( $case['conditions']['post_id'], $post_meta_name, $post_meta_value );
            }
          }
        }
      }
      if ( ! empty( $case['target_url'] ) ) {
        $this->go_to( $case['target_url'] );
      }
      $return = function_name();
      $this->assertEquals( $case['expected'], $return, $case['test_condition_name'] );
    }
  }
  ```
